Repository 100-hours-a-week/11-ellu-ai-summary-service, pull requests merged in 2025-07, with the labels that each got.

#178 refactor: 문서타입제한(#177)
  app/main.py
  models/wiki/doc_fetcher.py
  models/wiki/jina_processor.py
  models/wiki/wiki_fetcher.py
Labels: refactor

#185 refactor: 위키폴더구조변경(#184)
  app/dependencies.py
  app/main.py
  models/wiki/fetcher/doc_fetcher.py
  models/wiki/fetcher/wiki_fetcher.py
  models/wiki/wiki_processor.py
  models/wiki/wiki_retriever.py
  nodes/All_node.py
Labels: refactor

#187 feat:manager추가(#186)
  app/config.py
  models/wiki/retriever_manager.py
  nodes/All_node.py
Labels: feat

#189 feat: 유저 데이터 저장 part 수정(#187)
  app/main.py
  schemas/main_schema.py
Labels: feat

#191 feat:프롬프트 단순화 및 json pasrsing 단순화 (#190)
  models/llm/json_fixer.py
  nodes/All_node.py
  prompts/parsing_prompt.py
  prompts/prompt.py
Labels: feat

#207 206 feature stt 기능
  app/config.py
  app/exceptions.py
  app/main.py
  models/stt/audio_transcriber.py
  nodes/All_node.py
  nodes/graph.py
Labels: feat

#210 feature: STT변환 결과 엔드포인트 반환 및 노드 삭제 (#209)
  app/config.py
  app/main.py
  models/stt/audio_transcriber.py
  nodes/All_node.py
  nodes/graph.py
Labels: feat, refactor

#211 feature: stt 변환 결과 엔드포인트로 변환(#209)
  app/config.py
  nodes/graph.py
Labels: chore, refactor

#212 refactor: 로그 추가 (#209)
  app/main.py
Labels: chore

#213 fix: gemini api 연결 오류 수정 (#209)
  app/main.py
  models/stt/audio_transcriber.py
  requirements.txt
Labels: chore, fix

#216 feat: pinecone subtext 검색 구현(#215)
  models/pinecone/__init__.py
  models/pinecone/hybrid_retriever.py
Labels: feat

#217 feat: 역할 검색(#183)
  models/pinecone/hybrid_retriever.py
Labels: feat

#219 feat: 디비적용 및 fallback 구현(#218)
  models/wiki/basic_retriever.py
  models/wiki/retriever_manager.py
  nodes/All_node.py
Labels: feat

#221 refactor: prompt 수정(#220)
  prompts/prompt.py
Labels: refactor

#225 refactor: update config and requirements(#224)
  app/config.py
  requirements.txt
Labels: refactor
