Repository 100-hours-a-week/11-ellu-ai-summary-service, pull requests merged in 2025-05, with the labels that each got.

#17 refactor:코드수정
  llm/meeting_chain.py
  llm/wiki_chain.py
Labels: refactor

#13 feat: wiki정보 chromaDB 저장 기능 구현(#7)
  vectordb/chroma_store.py
Labels: feat

#11 feat: KoSimCSE 임베딩 모델 구현(#8)
  vectordb/embed_model.py
Labels: feat

#20 feat:상세일정 langchain구현(#9)
  llm/meeting_chain.py
Labels: feat

#24 feat:wiki chain (#23)
  llm/wiki_chain.py
Labels: feat

#25 feat:wiki retriever (#22)
  llm/wiki_retriever.py
Labels: feat

#26 feat: wiki 요약정보 임베딩 후 metadata와 함께 ChromaDB에 저장하는 기능 구현(#23)
  llm/wiki_chain.py
Labels: feat

#35 fix: import embed_model 파일 경로 수정(#34)
  vectordb/chroma_store.py
Labels: fix

#38 refactor: chroma_store 상태 반환 메세지 개선(#37)
  vectordb/chroma_store.py
Labels: refactor

#40 refactor: 임베딩 엔드포인트 구조 개선(#39)
  server.py
Labels: refactor

#45 feat : GPU 사용 코드 추가 (#44)
  llm/meeting_chain.py
  llm/wiki_chain.py
Labels: feat

#47 feat: webhook API 구현(#46)
  server.py
Labels: feat

#54 fix: Json parsing 수정 (#53)
  llm/meeting_chain.py
Labels: fix

#56 feat: semantic-release 적용
  .github/workflows/semantic-release.yml
Labels: feat

#64 fix: 대소문자 버그 수정
  llm/meeting_chain.py
Labels: fix

#65 feat: gitignore 추가 및 meeting_chain 프롬프팅 수정(#62)
  .gitignore
  chroma.sqlite3
  llm/meeting_chain.py
  llm/wiki_chain.py
Labels: feat, fix

#71 refactor: json-parsing-예외처리-수정(#69)
  chroma.sqlite3
  chroma/chroma.sqlite3
  llm/json_fixer.py
  llm/meeting_chain.py
  requirements.txt
  server.py
Labels: refactor

#75 refactor : 랭그래프 구현 및 프롬프팅 수정(#74)
  .gitignore
  llm/graph.py
  llm/json_fixer.py
  llm/meeting_chain.py
  server.py
Labels: refactor
